### ISSUE TITLE
v0.2

### ISSUE THREAD

**Issue by dmaskell92** [MyLegGuy/HigurashiPS3AutoC#1]
This errors and says the following is missing "vcruntime140d.dll" and "ucrtbased.dll". Those are Debug versions of DLLs, and it needs to be compiled in "Release mode".

Thank you. :D

**Comment by MyLegGuy** [comment]
Sorry for the late reply, I just got home. I'm working on it right now.

**Comment by MyLegGuy** [comment]
After working on this for 5 hours, I finally (maybe) fixed it.
Please try it, @dmaskell92 .

**Comment by dmaskell92** [comment]
Will test asap when I get access to this second computer without Visual Studio installed.

**Comment by MyLegGuy** [comment]
Tested on clean VM, it's okay.
